config/routes.rb
Dirlib::Application.routes.draw do

  get "messages/index"

  match "profile" => "users#show"  

  resources :books

  resources :statuses

  resources :posts

  resources :relationships

  resources :password_resets

  resources :messages

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  root :to => "home#index"

  resources :sessions

  resources :families

  resources :users do
    get 'assign', :on => :member
    put 'disable', :on => :member
    put 'activate', :on => :member
    get 'disabled', :on => :collection
  end

  resources :groups do
    resources :contacts
  end

  resources :categories do
    resources :posts
  end

  resources :contacts do
    put 'remove', :on => :member
    put 'activate', :on => :member
    get 'removed', :on => :collection
    get 'print', :on => :collection
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title, :speaker, :mdate 
  
  def self.search(search)
    where(['title like ? or speaker like ?', "%#{search}%", "%#{search}%"]).order("mdate desc") if search 
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.xml
  def index
    if params[:search]
      @messages = Message.search(params[:search]).page(params[:page]).per(10)
    else
      @messages = Message.order("mdate DESC").page(params[:page]).per(10)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.xml
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to(@message, :notice => 'Message was successfully created.') }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to(@message, :notice => 'Message was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to(messages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :speaker %><br />
    <%= f.text_field :speaker %>
  </div>
  <div class="field">
    <%= f.label :mdate %><br />
    <%= f.text_field :mdate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/_message_sidebar.html.erb
<% content_for :sidebar do %>
<li id="search-2" class="widget-container widget_search">
<h3>Search messages by title or speaker</h3>
<%= form_tag messages_path, :method => 'get' do %>
  <div><label class="screen-reader-text" for="search">Search for:</label> 
  <%= text_field_tag :search, params[:search] %> 
  <%= submit_tag "Search", :name => nil %>
  </div> 
<% end %>
</li>
<li id="recent-posts-2" class="widget-container"> 
  <h3 class="widget-title">My Messages</h3>   
    <ul>
        <li><%= link_to 'Show messages', messages_path %></li>
        <li><%= link_to 'Add message', new_message_path %></li>
    </ul>
</li>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<%= render "message_sidebar" %>

<h1>Listing messages</h1>

<div id="messages">
<% if @messages.present? %>
<ul>
<% @messages.each do |message| %>
  <li>
    <%= message.title %>
    <%= message.speaker %>
    <%= message.mdate %>
    <%= link_to 'Delete', message_path(message), :confirm => "This message will be deleted. Are you sure?", :method => :delete %>
  </li>
<% end %>
</ul>
<% else %>
<p>no messages found.</p>
<% end %>
</div>

<%= paginate @messages %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Mdate:</b>
  <%= @message.mdate %>
</p>

<p>
  <b>Title:</b>
  <%= @message.title %>
</p>

<p>
  <b>Speaker:</b>
  <%= @message.speaker %>
</p>
<% unless @message.verses.blank? %>
<p>
<b>Verses:</b>
  <% bible = ESV.new('IP') %>
  <% verses = bible_ref(@message.verses) %>
  <% verses.each do |v| %>
    <%= bible.doPassageQuery(v) %> 
  <% end %>
</p>
<% end %>

<p>
  <b>Summary:</b>
  <%= @message.summary %>
</p>

<p>
  <b>Application:</b>
  <%= @message.application %>
</p>

<p>
  <b>URL:</b>
  <%= @message.url %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>