config/routes.rb
Dirlib::Application.routes.draw do

  get "messages/index"

  match "profile" => "users#show"  

  resources :books

  resources :statuses

  resources :posts

  resources :relationships

  resources :password_resets

  resources :messages

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  root :to => "home#index"

  resources :sessions

  resources :families

  resources :users do
    get 'assign', :on => :member
    put 'disable', :on => :member
    put 'activate', :on => :member
    get 'disabled', :on => :collection
  end

  resources :groups do
    resources :contacts
  end

  resources :categories do
    resources :posts
  end

  resources :contacts do
    put 'remove', :on => :member
    put 'activate', :on => :member
    get 'removed', :on => :collection
    get 'print', :on => :collection
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :contact
  has_many :relationships
  has_many :contacts, :through => :relationships
  has_many :posts
  has_many :books
  has_many :messages

  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :admin, :contact_tokens, :active

  attr_reader :contact_tokens
  attr_accessor :password
  before_save :encrypt_password

  scope :active, where(:active => true).order("admin DESC, first_name")

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :first_name, :last_name
  validates_uniqueness_of :email

  def contact_tokens=(ids)
    self.contact_ids = ids.split(",")
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt) && user.active
      user
    else
      nil
    end
  end 

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def new_random_password
    self.password = ActiveSupport::SecureRandom.base64(6)
    self.password_confirmation = self.password
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64 
    end while User.exists?(column => self[column])
  end

  def name
    first_name + " " + last_name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.where(["id != ?", current_user.id]).active
  end

  def new
    @contacts = Contact.active_non_user
  end

  def show
    @contact = current_user.contact
  end

  def create
    # pre populate name and email from selected contact
    contact = Contact.find(params[:contact][:id])
    @user = User.new(:first_name => contact.first_name, :last_name => contact.last_name, :email => contact.email, :admin => params[:user][:admin]) 
    # random auto generate password
    @user.new_random_password 
    if @user.save
      # assign contact to user
      contact.update_attribute :user_id, @user.id
      # email confirmation to user
      UserMailer.registration_confirmation(@user).deliver
      redirect_to users_path, :notice => "User was successfully created!"
    else
      render "new" 
    end
  end

  def edit
  end

  def update
    params[:user].delete(:admin) unless current_user.admin
    params[:user].delete(:password) if params[:user][:password].blank?
    respond_to do |format|
      if @user.update_attributes(params[:user])
        if params[:user][:password]
          # email confirmation to user
          UserMailer.registration_confirmation(@user).deliver 
          if current_user.admin
            format.html { redirect_to(users_path, :notice => 'User was successfully updated.')}
          else
            format.html { redirect_to(@user, :notice => 'Password was successfully updated.')}
          end
        else 
          format.html { redirect_to(users_path, :notice => 'Contact assignments were successfully updated.')}
        end
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    if contact = @user.contact
      contact.update_attribute :user_id, nil
    end
    @user.destroy
    
    respond_to do |format|
      format.html { redirect_to users_url, :notice => "User has been successfully deleted." }
    end
  end

  # assign contacts
  def assign 
    @user = User.find(params[:id])
  end

  # set user to inactive rather than delete
  def disable
    @user = User.find(params[:id])
    if @user.update_attribute :active, false
      redirect_to users_url, :notice => "User has been successfully disabled."
    end 
  end

  def activate
    @user = User.find(params[:id])
    if @user.update_attribute :active, true
      redirect_to users_url, :notice => "User has been successfully activated."
    end
  end

  def disabled 
    @users = User.where(:active => false).order(:first_name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin_sidebar.html.erb
<% content_for :sidebar do %>
  <h3 class="widget-title">Users</h3>   
    <ul>
        <li><%= link_to 'Show active users', users_path %></li>
        <li><%= link_to 'Show disabled users', disabled_users_path %></li>
        <li><%= link_to 'Add user', new_user_path %></li>
    </ul>
  <br />
  <h3 class="widget-title">Groups</h3>   
    <ul>
        <li><%= link_to 'Show groups', groups_path %></li>
        <li><%= link_to 'Add group', new_group_path %></li>
    </ul>
  <br />
  <h3 class="widget-title">Statuses</h3>   
    <ul>
        <li><%= link_to 'Show statuses', statuses_path %></li>
        <li><%= link_to 'Add status', new_status_path %></li>
    </ul>
  <br />
  <h3 class="widget-title">Contacts</h3>   
    <ul>
        <li><%= link_to 'Show removed contacts', removed_contacts_path %></li>
        <li><%= link_to 'Show families', families_path %></li>
    </ul>
  <br />
  <h3 class="widget-title">Categories</h3>   
    <ul>
        <li><%= link_to 'Show categories', categories_path %></li>
        <li><%= link_to 'Add categories', new_category_path %></li>
    </ul>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="ui-widget">
      <div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
        <% for message in @user.errors.full_messages %>
        <span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span><%= message %><br />
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :login_email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %><br />
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <% if current_user.admin %>
  <div class="field">
    <%= f.check_box :admin %> <%= f.label :admin %>
  </div>
  <% end %>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/_profile_sidebar.html.erb
<% content_for :sidebar do %>
  <h3 class="widget-title">My Profile</h3>   
    <ul>
      <li><%= link_to 'Change password', edit_user_path(current_user) %></li>
      <li><a href="http://en.gravatar.com/" target="_blank">Add avatar</a></li>    
    </ul>
<% end %>

app/views/users/assign.html.erb
<%= render 'admin_sidebar' %>

<h1><%= @user.name %>'s Contacts</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="ui-widget">
      <div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
        <% for message in @user.errors.full_messages %>
        <span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span><%= message %><br />
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contact_tokens, "Contacts" %><br />
    <%= f.text_field :contact_tokens, "data-pre" => @user.contacts.order(:first_name).map{|c| {"id" => c.id, "name" => c.name + " - " + c.email}}.to_json %>
  </div>
  <p class="button"><%= f.submit :value => "Update User Contacts" %></p>
<% end %>

app/views/users/disabled.html.erb
<%= render 'users/admin_sidebar' %>

<h1>Disabled Users</h1>

Total <strong><%= @users.size %></strong> disabled users
<table>
  <tr>
    <th>Name</th><th>Email</th><th>Admin</th><th># Contacts</th><th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email%></td>
    <td><%= "Admin" if user.admin %></td>
    <td><%= link_to user.contacts.size, assign_user_path(user) %></td>
    <td><%= link_to 'Show', user.contact %>
    <% if can? :update, user%>
      | <%= link_to 'Activate', activate_user_path(user), :confirm => 'This user will be able to login again. Are you sure?', :method => :put %>
    <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/users/edit.html.erb
<%= render 'profile_sidebar' %>
<%= render 'form' %>

app/views/users/index.html.erb
<%= render 'admin_sidebar' %>

<h1>Active Users</h1>

Total <strong><%= @users.size %></strong> active users
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Admin</th>
    <th># Contacts</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= "Admin" if user.admin %></td>
    <td><%= link_to user.contacts.size, assign_user_path(user) %></td>
    <td>
    <%= link_to 'Edit', edit_user_path(user) %> | 
    <%= link_to 'Disable', disable_user_path(user), :confirm => 'This user will not be able to login. Are you sure?', :method => :put %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<%= render 'admin_sidebar' %>

<h1>New User</h1>

<%= form_for @user do |f| %> 
  <%= collection_select(:contact, :id, @contacts, :id, :name_email) %>
  <% if current_user.admin %>
  <div class="field">
    <%= f.check_box :admin %> <%= f.label :admin %>
  </div>
  <% end %>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<%= render 'profile_sidebar' %>
<h1><%= @contact.all_name %></h1>
<%= render 'contacts/contact_details' %>