config/routes.rb
Dirlib::Application.routes.draw do

  get "messages/index"

  match "profile" => "users#show"  

  resources :books

  resources :statuses

  resources :posts

  resources :relationships

  resources :password_resets

  resources :messages

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  root :to => "home#index"

  resources :sessions

  resources :families

  resources :users do
    get 'assign', :on => :member
    put 'disable', :on => :member
    put 'activate', :on => :member
    get 'disabled', :on => :collection
  end

  resources :groups do
    resources :contacts
  end

  resources :categories do
    resources :posts
  end

  resources :contacts do
    put 'remove', :on => :member
    put 'activate', :on => :member
    get 'removed', :on => :collection
    get 'print', :on => :collection
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates_presence_of :title, :content, :category_id

  def self.search(search)
    where(['title like ?', "%#{search}%"]).order("created_at desc") if search 
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
 
  #TODO: handle archive, report inappropiate 
  def index
    if params[:search]
      @posts = Post.search(params[:search]).page(params[:page])
    elsif params[:category_id]
      @category = Category.find(params[:category_id])
      @posts = @category.posts.order("created_at desc").page(params[:page])
    else
      @posts = Post.order("created_at desc").page(params[:page])
    end
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    # @post.user_id = current_user.id
    @post = current_user.posts.build(params[:post])
    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_bulletin_sidebar.html.erb
<% content_for :sidebar do %>
<li id="search-2" class="widget-container widget_search">
<h3>Search posts by title</h3>
<%= form_tag posts_path, :method => 'get' do %>
  <div><label class="screen-reader-text" for="search">Search for:</label> 
  <%= text_field_tag :search, params[:search] %> 
  <%= submit_tag "Search", :name => nil %>
  </div> 
<% end %>
</li>
<li id="recent-posts-2" class="widget-container"> 
  <h3 class="widget-title">My Posts</h3>   
    <ul>
        <li><%= link_to 'Show posts', posts_path %></li>
        <li><%= link_to 'Add post', new_post_path %></li>
    </ul>
</li>
<li id="recent-posts-2" class="widget-container"> 
  <h3 class="widget-title">Filter by Category</h3>   
    <ul>
      <% Category.order(:name).each do |category| %>
        <li><%= link_to category.name, category_posts_url(category) %></li>
      <% end %>
    </ul>
</li>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <div class="ui-widget">
        <div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
          <% for message in @post.errors.full_messages %>
          <span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span><%= message %><br />
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 4, :cols => 60 %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select :category_id, Category.order(:name).map {|cat| [cat.name, cat.id]}, {:include_blank => true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render 'bulletin_sidebar' %>
<h1>Editing post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'bulletin_sidebar' %>
<h1>Bulletin posts</h1>
<% if params[:category_id] %>
<strong><%= @category.name %></strong><br />
<% end %>

  <ul>
    <% @posts.each do |post| %>
      <li><%= post.created_at.strftime("%b %d") %> <%= link_to post.title, post %> by <%= link_to post.user.name, contact_path(post.user.contact) %></li>
    <% end %>
  </ul>

<%= paginate @posts %>

app/views/posts/index.mobile.erb
<div data-role="header">
  <h1>Listing posts</h1>
  <%= link_to 'Add', new_post_path, "data-icon" => "plus", "class" => "ui-btn-right" %>
</div>

<div data-role="content">
  <ul data-role="listview">
    <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post %>
      <%= link_to 'edit post', edit_post_path(post), "data-icon" => "gear" %>
    </li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<%= render 'bulletin_sidebar' %>
<h1>New bulletin post</h1>

<%= render 'form' %>

app/views/posts/new.mobile.erb
<div data-role="header">
  <h1>New Post</h1>
</div>

<div data-role="content">
</div>

app/views/posts/show.html.erb
<%= render 'bulletin_sidebar' %>

<h2 class="entry-title"><%= @post.title %></h2>
<div class="entry-meta">
  <span class="meta-prep meta-prep-author">Posted on</span>
  <span class="entry-date"><%= @post.created_at.strftime("%m/%d/%Y") %></span>
  <span class="meta-sep">by</span>
  <span class="author vcard"><%= link_to @post.user.name, contact_path(@post.user.contact) %></span> 
  <span class="meta-sep">in</span>
  <span class="cat-links"><%= link_to @post.category.name, category_posts_path(@post.category) %></span>
</div>
<div class="entry-content">
  <p><%= @post.content %></p>
</div>

<% if can? :update, @post %>
<%= link_to 'Edit post', edit_post_path(@post) %> |
<%= link_to 'Destroy post', @post, :confirm => 'Are you sure?', :method => :delete %></td>
<% end %>

app/views/posts/show.mobile.erb
<div data-role="header">
  <h1><%= @post.title %></h1>
  <%= link_to 'List Posts', posts_url, "class" => "ui-btn-right" %>
</div>

<div data-role="content">
  <%= @post.content %>
</div>