config/routes.rb
Dirlib::Application.routes.draw do

  get "messages/index"

  match "profile" => "users#show"  

  resources :books

  resources :statuses

  resources :posts

  resources :relationships

  resources :password_resets

  resources :messages

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  root :to => "home#index"

  resources :sessions

  resources :families

  resources :users do
    get 'assign', :on => :member
    put 'disable', :on => :member
    put 'activate', :on => :member
    get 'disabled', :on => :collection
  end

  resources :groups do
    resources :contacts
  end

  resources :categories do
    resources :posts
  end

  resources :contacts do
    put 'remove', :on => :member
    put 'activate', :on => :member
    get 'removed', :on => :collection
    get 'print', :on => :collection
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Directory</title>
  <%= stylesheet_link_tag "style", "mystyle", "token-input", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/themes/smoothness/jquery-ui.css" %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js" %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="wrapper" class="hfeed">
  <div id="header">
    <div id="masthead">
      <div id="branding" role="banner">
                <h1 id="site-title">
          <span>
            <a href="" title="Directory and Library" rel="home">Directory and Library</a>
          </span>

        </h1>
        <div id="site-description">Sharing resources within your church</div>

                </div><!-- #branding -->

      <div id="user_nav">
        <% if current_user %>
          Logged in as <%= current_user.name %> |
          <%= link_to "Log out", log_out_path %>
        <% else %>
          <%= link_to "Log in", log_in_path %>
        <% end %> |
        <% if mobile_device? %>
          <%= link_to "Full Site", :mobile => 0 %>
        <% else %>
          <%= link_to "Mobile Site", :mobile => 1 %>
        <% end %>
      </div>
      <div id="access" role="navigation">
                <div class="skip-link screen-reader-text"><a href="#content" title="Skip to content">Skip to content</a></div>

                <div class="menu">
<ul><li class="page_item current_page_item"><%= link_to 'Home', root_url %></a></li>
<% if current_user %>
<li class="page_item"><%= link_to 'Profile', profile_path %></li>
<li class="page_item"><%= link_to 'Directory', contacts_path %></li>
<li class="page_item"><%= link_to 'Library', books_path %></li>
<li class="page_item"><%= link_to 'Bulletin', posts_path %></li>
  <% if current_user.admin %>
<li class="page_item"><%= link_to 'Admin', users_path %></li>
  <% end %>
<% end %>
</ul></div>
      </div><!-- #access -->
    </div><!-- #masthead -->
  </div><!-- #header -->

  <div id="main">

    <div id="container">
      <div id="content" role="main">
<% flash.each do |name, msg| %>
<div class="ui-widget">
  <div class="ui-state-highlight ui-corner-all" style="padding: 0 .7em;">
  <%= msg %><br />
  </div>
</div>
<% end %>
<%= yield %>
      </div><!-- #content -->
    </div><!-- #container -->

    <div id="primary" class="widget-area" role="complementary">
      <ul class="xoxo">
      <%= yield :sidebar%>
</ul>
    </div><!-- #primary .widget-area -->

  </div><!-- #main -->

  <div id="footer" role="contentinfo">
    <div id="colophon">
      <div id="site-info">
        Please email feedbacks to the webmaster: johannchen @ gmail
      </div><!-- #site-info -->
    </div><!-- #colophon -->
  </div><!-- #footer -->
</div><!-- #wrapper -->

</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <title>Church Directory</title>
<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0a4/jquery.mobile-1.0a4.min.css" />
  <script type="text/javascript" src="http://code.jquery.com/jquery-1.5.2.min.js"></script>
  <script type="text/javascript" src="http://code.jquery.com/mobile/1.0a4/jquery.mobile-1.0a4.min.js"></script>

<!--
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0b1/jquery.mobile-1.0b1.min.css" />
  <script type="text/javascript" src="http://code.jquery.com/jquery-1.6.1.min.js"></script>
  <script type="text/javascript" src="http://code.jquery.com/mobile/1.0b1/jquery.mobile-1.0b1.min.js"></script>
-->
  <%= csrf_meta_tag %>

</head>
<body>
  <div data-role="page">
    <%= yield %>
  </div>
</body>
</html>